[package]
name = "hftbacktest"
version = "0.9.4"
edition = "2024"
authors = ["nkaz001 <nkaz001@protonmail.com>"]
license = "MIT"
documentation = "https://docs.rs/hftbacktest/"
repository = "https://github.com/nkaz001/hftbacktest/"
readme = "README.md"
description = "A high-frequency trading and market-making backtesting tool accounts for limit orders, queue positions, and latencies, utilizing full tick data for trades and order books."
keywords = [
    "quantitative",
    "trading",
    "backtesting",
    "cryptocurrency",
    "hft"
]
categories = ["finance", "mathematics", "science", "algorithms", "simulation"]
rust-version = "1.91.1"

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
rust_decimal = "1.43"
csv = "1.4"
flate2 = "1"
tempfile = "3"
anyhow = "1.0.100"
thiserror = "2.0.17"
zip = "8.6.0"
npyz = { version = "0.9.1", features = ["derive"] }
